// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9WUcvQOU2KqcR_qvVyk7as76VIAwyTR8',
    appId: '1:492876220070:web:0d82dddcd1509a1b1b1667',
    messagingSenderId: '492876220070',
    projectId: 'pergam-b6da1',
    authDomain: 'pergam-b6da1.firebaseapp.com',
    storageBucket: 'pergam-b6da1.appspot.com',
    measurementId: 'G-FC221ECSFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFg_pQGUUnWN4onm_fmwX6ATNgeDfppk',
    appId: '1:492876220070:android:998ebdf3632a53f61b1667',
    messagingSenderId: '492876220070',
    projectId: 'pergam-b6da1',
    storageBucket: 'pergam-b6da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKyJnT2eQyV0hzUq0Hov1BIc2lxcFOu4',
    appId: '1:492876220070:ios:24d3669140bb31141b1667',
    messagingSenderId: '492876220070',
    projectId: 'pergam-b6da1',
    storageBucket: 'pergam-b6da1.appspot.com',
    iosClientId:
        '492876220070-606om8br19nseehnij8pieapp2ujrh8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pergam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKyJnT2eQyV0hzUq0Hov1BIc2lxcFOu4',
    appId: '1:492876220070:ios:24d3669140bb31141b1667',
    messagingSenderId: '492876220070',
    projectId: 'pergam-b6da1',
    storageBucket: 'pergam-b6da1.appspot.com',
    iosClientId:
        '492876220070-606om8br19nseehnij8pieapp2ujrh8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pergam',
  );
}
